// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMnZhaaB5rg-MPeBzas8o-8JTlyWzToZ8',
    appId: '1:782965043473:web:ac72783070bc0fbc0b5cb0',
    messagingSenderId: '782965043473',
    projectId: 'money-mate-mobile',
    authDomain: 'money-mate-mobile.firebaseapp.com',
    storageBucket: 'money-mate-mobile.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI0rdK0wlFgEWpbRcm0xiMb8rX5iftnng',
    appId: '1:782965043473:android:51360840273bdd720b5cb0',
    messagingSenderId: '782965043473',
    projectId: 'money-mate-mobile',
    storageBucket: 'money-mate-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtxyLLwV9M1gvr8vqXnWmrLcDxeUZPUoI',
    appId: '1:782965043473:ios:daeade40386bd5e50b5cb0',
    messagingSenderId: '782965043473',
    projectId: 'money-mate-mobile',
    storageBucket: 'money-mate-mobile.firebasestorage.app',
    iosBundleId: 'com.abpProject.moneyMateMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtxyLLwV9M1gvr8vqXnWmrLcDxeUZPUoI',
    appId: '1:782965043473:ios:daeade40386bd5e50b5cb0',
    messagingSenderId: '782965043473',
    projectId: 'money-mate-mobile',
    storageBucket: 'money-mate-mobile.firebasestorage.app',
    iosBundleId: 'com.abpProject.moneyMateMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMnZhaaB5rg-MPeBzas8o-8JTlyWzToZ8',
    appId: '1:782965043473:web:5dc0dc354627a6ed0b5cb0',
    messagingSenderId: '782965043473',
    projectId: 'money-mate-mobile',
    authDomain: 'money-mate-mobile.firebaseapp.com',
    storageBucket: 'money-mate-mobile.firebasestorage.app',
  );
}
